import express from 'express'
import mysql from 'mysql'
import cors from 'cors'
import cookieParser from 'cookie-parser'
import bcrypt, { hash } from 'bcrypt'
import jwt from 'jsonwebtoken'
import multer from 'multer'
import path from 'path'

const app = express();
app.use(cors());
app.use(cookieParser());
app.use(express.json());
app.use(express.static('public'));

const con = mysql.createConnection({
    host: "localhost",
    user: "root",
    password: "",
    database: "employeemanag",
})

const storage = multer.diskStorage({
    destination: (req, file, cb)=>{
        cb(null, 'public/images')
    },
    filename:(req, file, cb)=>{
        cb(null, file.fieldname + '_' + Date.now() + path.extname(file.originalname))
    },
})

const upload = multer({
    storage: storage,
})

con.connect(function(err){
    if(err){
        console.log("error in connection");
    }
    else{
        console.log("connected");
    }
})

app.post('/login', (req, res) =>{
    const sql = "SELECT * FROM user WHERE email= ? AND password = ?"
    con.query(sql, [req.body.user, req.body.psw], (err, result)=>{
        if(err) return res.json({Status: "error", Error: "error in running query"});
        if(result.length > 0) return res.json({Status: "success"})
        else return res.json({Status: "error", Error: "wrong email or password"})
    })
})

app.post('/creat', upload.single('image'), (req, res) => {
    // Assuming that you have a table 'employee' in your database
    const sql = "INSERT INTO employee (name, salary, email, password, address, image) VALUES (?, ?, ?, ?, ?, ?)";
    
    const { name, salary, email, password, address } = req.body;
    
    bcrypt.hash(password.toString(), 10, (err, hashed) => {
        if (err) {
            console.error(err);
            return res.json({ Status: "error", Error: "error hashing password" });
        }
        
        const image = req.file.filename; // Use the filename generated by Multer
        const values = [name, salary, email, hashed, address, image];
        
        con.query(sql, values, (err, result) => {
            if (err) {
                console.error(err);
                return res.json({ Status: "error", Error: "error in running query" });
            }
            
            if (result.affectedRows > 0) {
                console.log("Insertion is a Success!!!!!!\n");
                return res.json({ Status: "success" });
            } else {
                console.error(err);
                return res.json({ Status: "error", Error: "Insertion failed" });
            }
        });
    });
});

app.get('/getEmployee', (req, res)=>{
    const sql='SELECT * FROM employee'
    con.query(sql, (err, result)=>{
        if(err){
            return res.json({Error: 'Error in getting emplyees from data base'})
        }
        return res.json({Status: 'success', Result: result})
    })
})

app.get('/get/:id', (req, res)=>{
    const id = req.params.id;
    const sql = 'SELECT * FROM employee WHERE id=?'
    con.query(sql, [id], (err, result)=>{
        if(err) return res.json({Error: 'error in getting employee'});
        return res.json({Status: 'success', Result: result});
    })
})

app.post('/edit', (req, res) => {
    const sql = "UPDATE employee SET name = ?, salary = ?, email = ?, address = ? WHERE id = ?";    
    const { name, salary, email, address, id } = req.body;
        
        const values = [name, salary, email, address, id];
        
        con.query(sql, values, (err, result) => {
            if (err) {
                console.error(err);
                return res.json({ Status: "error", Error: err });
            }
            
            if (result.affectedRows > 0) {
                console.log("Update is a Success!!!!!!\n");
                return res.json({ Status: "success" });
            } else {
                console.error(err);
                return res.json({ Status: "error", Error: err });
            }
        });
    console.log(req.body)
    });
    
app.delete('/delete/:id', (req, res)=>{
    const id = req.params.id;
    const sql = 'DELETE FROM employee WHERE id=?';
    con.query(sql, [id], (err, result)=>{
        if(err){
            return res.json({Error: err})
        }
        console.log(result);
        return res.json({Status: 'success', Result: result})
    })
})

app.listen(8081, ()=> {
    console.log("running");
})